/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ConfirmationDialog: typeof import('./src/components/form/ConfirmationDialog.vue')['default']
    DynamicForm: typeof import('./src/components/form/DynamicForm.vue')['default']
    FormCheckboxField: typeof import('./src/components/form/FormCheckboxField.vue')['default']
    FormNumberField: typeof import('./src/components/form/FormNumberField.vue')['default']
    FormRadioField: typeof import('./src/components/form/FormRadioField.vue')['default']
    FormSelectField: typeof import('./src/components/form/FormSelectField.vue')['default']
    FormTextField: typeof import('./src/components/form/FormTextField.vue')['default']
    Formulario: typeof import('./src/components/formulario.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidationDialog: typeof import('./src/components/form/ValidationDialog.vue')['default']
  }
}
